// <auto-generated />
using Masjid.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masjid.Migrations
{
    [DbContext(typeof(MasjidDbContext))]
    [Migration("20230225164235_Db Reconstruction")]
    partial class DbReconstruction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masjid.Models.AftSchoolProgram", b =>
                {
                    b.Property<int>("AftSchoolProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AftSchoolProgramId"));

                    b.Property<string>("AftSchoolProgramDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AftSchoolProgramPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AftSchoolProgramTimePlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AftSchoolProgramTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AftSchoolProgramId");

                    b.ToTable("AftSchoolPrograms");
                });

            modelBuilder.Entity("Masjid.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("EventDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventNarrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Masjid.Models.Feed", b =>
                {
                    b.Property<int>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedId"));

                    b.Property<string>("FeedColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedNarrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("Masjid.Models.Hadith", b =>
                {
                    b.Property<int>("HadithId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HadithId"));

                    b.Property<string>("HadithDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadithNarrator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HadithId");

                    b.ToTable("Hadiths");
                });

            modelBuilder.Entity("Masjid.Models.IslamicClasse", b =>
                {
                    b.Property<int>("IslamicClasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslamicClasseId"));

                    b.Property<string>("ClassDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IslamicClassGuest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IslamicClassTime_Place")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IslamicClasseId");

                    b.ToTable("IslamicClasses");
                });

            modelBuilder.Entity("Masjid.Models.PrayerTime", b =>
                {
                    b.Property<int>("PrayerTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrayerTimeId"));

                    b.Property<string>("Asr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dhur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fajr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jummah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maghrib")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrayerTimeId");

                    b.ToTable("PrayerTimes");
                });

            modelBuilder.Entity("Masjid.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Masjid.Models.YouthProgram", b =>
                {
                    b.Property<int>("YouthProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YouthProgramId"));

                    b.Property<string>("YouthProgramDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouthProgramGuest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouthProgramPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouthProgramTimePlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouthProgramTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YouthProgramId");

                    b.ToTable("YouthPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
